---
title: "Publications"
page-layout: full
format:
  html:
    css: styles.css
---

::: {.centered-content}

Publications are listed in chronological order.

Identification key:
(**PI**,
*Postdocs*,
**Graduate Students†**,
**Staff and Technicians***)

---

::: {.pub-list}

69\. Jones, B. L. H., **Costa, S.<sup>†</sup>**, *James, W. R.*, Adams, A., Boucek, R., **Santos, R. O.**, **Rehage, J.** (2026). Six decades of fishery change inferred from fishers’ recollections of their best catches. [doi](https://doi.org/10.21203/rs.3.rs-9115805/v1)

68\. **Kabat, L. J.<sup>†</sup>**, Crowl, T. A., Estruche-Santos, Á. S., Cheshire, J., *James, W. R.*, ... (2026). Comparison of tagging techniques for tracking freshwater tropical shrimp: assessment of survival and behaviour as a function of tag type. *Crustaceana*, 99(4), 413–437. [doi](https://doi.org/10.1163/15685403-bja10515)

67\. Linenfelser, J. O., *James, W. R.*, Rezek, R. J., **Santos, R. O.**, Frankovich, T. A., ... (2026). Isotopic insights into nutrient contributions and transport pathways in north-central Florida Bay. *Estuarine, Coastal and Shelf Science*, 109765, 15 pages. [doi](https://doi.org/10.1016/j.ecss.2026.109765)

66\. **Rivas, N.<sup>†</sup>**, *James, W. R.*, **Bautista, V.<sup>†</sup>**, **Sandquist, M.<sup>*</sup>**, Guerriero, A. F., Arias, S. B., ... (2025). Tipping the balance: Reef community shifts after a regional urchin population collapse. [doi](https://doi.org/10.1007/s00338-026-02822-1)

65\. **Sturges, J. W.<sup>*</sup>**, *James, W. R.*, Rezek, R. J., **Santos, R. O.**, White, M., **Badlowski, G. A.<sup>*</sup>**, ... (2026). Variation in food web reliance on green and brown energy pathways across ecosystem gradients. *PLOS ONE*, 21(2), 21 pages. [doi](https://doi.org/10.1371/journal.pone.0336521)

64\. **Goldner, V. S.<sup>*</sup>**, **White, M.<sup>†</sup>**, Eggenberger, C. W., **Jones, A. A.<sup>†</sup>**, **Atkinson, C. C.<sup>†</sup>**, ... (2026). Gone but not forgotten: Collaborative telemetry network provides insight into out-of-system movements of Common Snook. *Marine and Coastal Fisheries*, 18(1), 13 pages. [doi](https://doi.org/10.1093/mcfafs/vtaf050)

63\. *Rodemann, J.*, **White, M.<sup>†</sup>**, *James, W. R.*, Griffin, L. P., **Costa, S. V.<sup>†</sup>**, Furman, B. T., ... (2025). Hierarchical habitat selection by a predatory fish in a patchy seascape. *Scientific Reports*. 15, 13 pages. [doi](https://doi.org/10.1038/s41598-025-27322-0)

62\. Eggenberger, C. W., Viadero, N., **Santos, R. O.**, Papastamatiou, Y., Price, R., ... (2025). Seascape heterogeneity and predictability drive movement strategy selection in estuarine predators. *Journal of Animal Ecology*, 94(12), 2671–2686. [doi](https://doi.org/10.1111/1365-2656.70164)

61\. Massie, J. A., Rezek, R. J., *James, W. R.*, **Santos, R. O.**, Viadero, N. M., Boucek, R. E., ... (2025). Linking a seasonal freshwater prey subsidy to the body condition of an estuarine consumer in a subtropical coastal river. *Scientific Reports*, 15(1), 15 pages. [doi](https://doi.org/10.1038/s41598-025-25211-0)

60\. **Rehage, J. S.**, Castillo, N. A., **Distrubell, A.<sup>†</sup>**, **Trabelsi, S.<sup>*</sup>**, **Santos, R. O.**, *James, W. R.*, ... (2025). A multi-estuary assessment of pharmaceutical exposure and risk of pharmacological effects in a recreational fishery. *Environmental Toxicology and Chemistry*, 44(10), 16 pages. [doi](https://doi.org/10.1093/etojnl/vgaf125)

59\. **White, M.<sup>†</sup>**, *James, W. R.*, *Lesser, J. S.*, Rezek, R. J., *Rodemann, J.*, Boucek, R. E., ... (2025). Linking hydrology, temperature, and energetics: Global change implications for the foraging ecology of a generalist predator. *Marine and Coastal Fisheries*, 17(5), 13 pages. [doi](https://doi.org/10.1093/mcfafs/vtaf031)

58\. Massie, J. A., Rezek, R. J., **Santos, R. O.**, *James, W. R.*, Viadero, N. M., Boucek, R. E., ... (2025). Long-term patterns in the relative abundance of Common Snook as a factor of shifting environmental conditions in the Florida coastal Everglades. *Marine and Coastal Fisheries*, 17(5), 14 pages. [doi](https://doi.org/10.1093/mcfafs/vtaf026)

57\. **Viadero, N. M.<sup>†</sup>**, Massie, J. A., Eggenberger, C. W., *James, W. R.*, Boucek, R. E., ... (2025). Between a dry marsh and a salty place: Estuarine habitat suitability for a freshwater fish (Florida bass) and implications for ecosystem restoration and climate change. *Estuaries and Coasts*, 48(5), 124. [doi](https://doi.org/10.1007/s12237-025-01561-w)

56\. *Rodemann, J.*, *James, W. R.*, **Rehage, J. S.**, Furman, B. T., Pittman, S. J., ... (2025). Response of submerged aquatic vegetation seascapes to a large-scale seagrass die-off: A case study in Florida Bay. *Estuarine, Coastal and Shelf Science*, 318, 109221. [doi](https://doi.org/10.1016/j.ecss.2025.109221)

55\. *James, W. R.*, **Castillo, N. A.<sup>†</sup>**, **Distrubell, A.<sup>†</sup>**, **Trabelsi, S.<sup>*</sup>**, **Santos, R. O.**, Cerveny, D., ... (2025). Occurrence of pharmaceuticals in muscle tissue of red drum (*Sciaenops ocellatus*) across subtropical estuaries: Comparison to blood plasma and implications for human exposure. *Science of the Total Environment*, 972, 179106. [doi](https://doi.org/10.1016/j.scitotenv.2025.179106)

54\. **Santos, R. O.**, *James, W. R.*, **Rehage, J. S.**, **Eggenberger, C. W.<sup>†</sup>**, *Lesser, J. S.*, ... (2025). Trophic niche dynamics of two fish mesoconsumers in adjacent coastal habitats with varying nutrient regimes. *Oecologia*, 207(3), 43. [doi](https://doi.org/10.1007/s00442-025-05680-w)

53\. **Santos, R. O.**, **White, M.<sup>†</sup>**, *James, W. R.*, **Viadero, N. M.<sup>†</sup>**, **Massie, J. A.<sup>†</sup>**, Boucek, R. E., ... (2025). Cause and consequences of Common Snook (*Centropomus undecimalis*) space use specialization in a subtropical riverscape. *Scientific Reports*, 15(1), 2004. [doi](https://doi.org/10.1038/s41598-024-82158-4)

52\. Jones, B. L. H., **Santos, R. O.**, *James, W. R.*, Shephard, S., Adams, A. J., Boucek, R. E., ... (2025). Stakeholder diversity matters: employing the wisdom of crowds for data-poor fisheries assessments. *Scientific Reports*, 15(1), 440. [doi](https://doi.org/10.1038/s41598-024-84970-4)

51\. **Castillo, N. A.<sup>†</sup>**, **Santos, R. O.**, *James, W. R.*, Rezek, R., Cerveny, D., Boucek, R. E., ... (2024). Widespread pharmaceutical exposure at concentrations of concern for a subtropical coastal fishery: Bonefish (*Albula vulpes*). *Marine Pollution Bulletin*, 209, 14 pages. [doi](https://doi.org/10.1016/j.marpolbul.2024.117143)

50\. Kahmann, G., **Rehage, J. S.**, **Massie, J. A.<sup>*</sup>**, Nelson, J. A., **Santos, R. O.**, **Viadero, N. M.<sup>*</sup>**, ... (2024). Trophic niche of a nonnative invader and environmental drivers of its increasing populations in the coastal Everglades. *Biological Invasions*, 26(12), 18 pages. [doi](https:// doi. org/ 10. 1007/ s10530- 024- 03444-w) 

49\. Castillo, N. A., **Santos, R. O.**, *James, W. R.*, Rezek, R., Cerveny, D., Boucek, R. E., . . . **Rehage, J. S.** (2024). Differential tissue distribution of pharmaceuticals in a wild subtropical marine fish. *Aquatic Toxicology*, 275, 14 pages. [doi](https://doi.org/10.1016/j.aquatox.2024.107064)

48\. Castillo, N. A., *James, W. R.*, **Santos, R. O.**, Rezek, R., Cerveny, D., Boucek, R. E., . . . Rehage, J. S. (2024). Identifying pathways of pharmaceutical exposure in a mesoconsumer marine fish. *Journal of Hazardous Materials*, 477, 16 pages. [doi](https://doi.org/10.1016/j.jhazmat.2024.135382)

47\. Jones, B. L. H., **Santos, R. O.**, *James, W. R.*, Costa, S. V., Adams, A. J., Boucek, R. E., . . . Rehage, J. S. (2024). New directions for Indigenous and local knowledge research and application in fisheries science: Lessons from a systematic review. *Fish and Fisheries*, 25(4), 647–671. [doi](https://doi.org/10.1111/faf.12831)

46\. *James, W. R.*, Furman, B. T., Rodemann, J. R.†, Costa, S. V., Fratto, Z. W.*, Nelson, J. A., . . . **Santos, R. O.** (2024). Widespread habitat loss leads to ecosystem-scale decrease in trophic function. *Global Change Biology*, 30(4), 12 pages. [doi](https://doi.org/10.1111/gcb.17263)

45\. Castillo, N. A., *James, W. R.*, **Santos, R. O.**, Rezek, R., Cerveny, D., Boucek, R. E., . . . Rehage, J. S. (2024). Understanding pharmaceutical exposure and the potential for effects in marine biota: A survey of bonefish (*Albula vulpes*) across the Caribbean Basin. *Chemosphere*, 349. [doi](https://doi.org/10.1016/j.chemosphere.2023.140949)

44\. Flaherty-Walia, K. E., Gervasi, C. L., Davis, J. P., **Trabelsi, S.<sup>*</sup>**, Fratto, Z., **Santos, R. O.**, . . . **Rehage, J. S.** (2023). Seines and baited remote underwater video document consistent spatiotemporal patterns in nekton communities of subtropical coastal habitats. MARINE ECOLOGY PROGRESS SERIES, 722, 37-64. [doi](https://doi.org/10.3354/meps14418)

43\. Gervasi, C. L., Karnauskas, M., **Rios, A.<sup>†</sup>**, **Santos, R. O.**, *James, W. R.*, *Rezek, R. J.*, & **Rehage, J. S.** (2023). Rapid approach for assessing an unregulated fishery using a series of data-limited tools. MARINE AND COASTAL FISHERIES, 15(5), 22 pages. [doi](https://doi.org/10.1002/mcf2.10270)

42\. Calhoun-Grosch, S., Foster, E. M., *James, W. R.*, **Santos, R. O.**, **Rehage, J. S.**, & Nelson, J. A. (2023). Trophic Niche Metrics Reveal Long-Term Shift in Florida Bay Food Webs. ECOSYSTEMS, 26(6), 1183-1194. [doi](https://doi.org/10.1007/s10021-023-00825-5)

41\. *Rezek, R. J.*, **Massie, J. A.<sup>†</sup>**, Nelson, J. A., **Santos, R. O.**, **Viadero, N. M.<sup>†</sup>**, *James, W. R.*, . . . **Rehage, J. S.** (2023). The effects of temperature and flooding duration on the structure and magnitude of a floodplain prey subsidy. FRESHWATER BIOLOGY, 68(9), 1518-1529. [doi](https://doi.org/10.1111/fwb.14145)

40\. **Rodemann, J. R.<sup>†</sup>**, *James, W. R.*, **Rehage, J. S.**, Baktoft, H., **Costa, S.<sup>†</sup>**, Ellis, R., . . . **Santos, R. O.** (2023). Residency and fine-scale habitat use of juvenile goliath grouper (<i>Epinephelus itajara</i>) in a mangrove nursery. BULLETIN OF MARINE SCIENCE, 99(2), 111-117. [doi](https://doi.org/10.5343/bms.2022.0061)

39\. Campbell, L. J., **Castillo, N. A.<sup>†</sup>**, Dunn, C. D., Perez, A., Schmitter-Soto, J. J., Mejri, S. C., . . . Goldberg, T. L. (2023). Viruses of Atlantic Bonefish (<i>Albula vulpes</i>) in Florida and the Caribbean show geographic patterns consistent with population declines. ENVIRONMENTAL BIOLOGY OF FISHES, 106(2), 303-317. [doi](https://doi.org/10.1007/s10641-022-01306-9)

38\. Boucek, R. E., **Rehage, J. S.**, **Castillo, N. A.<sup>†</sup>**, Dwoskin, E., Lombardo, S. M., **Santos, R. O.**, . . . Adams, A. J. (2023). Using recreational tournament records to construct a 53-year time series of the Florida Keys recreational Bonefish fishery. ENVIRONMENTAL BIOLOGY OF FISHES, 106(2), 279-291. [doi](https://doi.org/10.1007/s10641-022-01299-5)

37\. *Rezek, R. J.*, *James, W. R.*, **Bautista, V.<sup>*</sup>**, Zink, I., **Rehage, J. S.**, & **Santos, R. O.** (2023). Temporal trends of Biscayne Bay pink shrimp fisheries catch, economic indicators, and potential interactions with South Florida recreational flats fisheries. ENVIRONMENTAL BIOLOGY OF FISHES, 106(2), 361-379. [doi](https://doi.org/10.1007/s10641-022-01314-9)

36\. **Massie, J. A.<sup>†</sup>**, **Santos, R. O.**, *Rezek, R. J.*, *James, W. R.*, **Viadero, N. M.<sup>†</sup>**, Boucek, R. E., . . . **Rehage, J. S. (2022)**. Primed and cued: long-term acoustic telemetry links interannual and seasonal variations in freshwater flows to the spawning migrations of Common Snook in the Florida Everglades. MOVEMENT ECOLOGY, 10(1), 20 pages. [doi](https://doi.org/10.1186/s40462-022-00350-5)

35\. Gervasi, C. L., Nelson, J. A., Swart, P. K., **Santos, R. O.**, *Rezek, R. J.*, *James, W. R.*, . . . **Rehage, J. S.** (2022). Otolith stable isotope micro-sampling to discriminate poorly studied stocks: Crevalle Jack in the eastern gulf of Mexico. ESTUARINE COASTAL AND SHELF SCIENCE, 278, 14 pages. [doi](https://doi.org/10.1016/j.ecss.2022.108130)

34\. **Rehage, J. S.**, Boucek, R. E., **Santos, R. O.**, **Massie, J. A.<sup>†</sup>**, **Viadero, N. M.<sup>†</sup>**, & *Rezek, R. J.* (2022). Untangling Flow-Ecology Relationships: Effects of Seasonal Stage Variation on Common Snook Aggregation and Movement Rates in the Everglades. ESTUARIES AND COASTS, 45(7), 2059-2069. [doi](https://doi.org/10.1007/s12237-022-01065-x)

33\. Gervasi, C. L., **Massie, J. A.<sup>†</sup>**, **Rodemann, J.<sup>†</sup>**, **Trabelsi, S.<sup>*</sup>**, **Santos, R. O.**, & **Rehage, J. S.** (2022). Recreational Angler Contributions to Fisheries Management Are Varied and Valuable: Case Studies from South Florida. FISHERIES, 47(11), 469-477. [doi](https://doi.org/10.1002/fsh.10823)

32\. *James, W. R.*, **Santos, R. O.**, **Rodemann, J. R.<sup>†</sup>**, *Rezek, R. J.*, Fratto, Z. W., Furman, B. T., . . . Nelson, J. A. (2022). Widespread seagrass die-off has no legacy effect on basal resource use of seagrass food webs in Florida Bay, USA. ICES JOURNAL OF MARINE SCIENCE, 79(6), 1831-1842. [doi](https://doi.org/10.1093/icesjms/fsac112)

31\. Patrick, C. J., Kominoski, J. S., McDowell, W. H., Branoff, B., Lagomasino, D., Leon, M., . . . Zou, X. (2022). A general pattern of trade-offs between ecosystem resistance and resilience to tropical cyclones. SCIENCE ADVANCES, 8(9), 10 pages. [doi](https://doi.org/10.1126/sciadv.abl9155)


30\. **Santos, R. O.**, *James, W. R.*, Nelson, J. A., **Rehage, J. S.**, Serafy, J., Pittman, S. J., & Lirman, D. (2022). Influence of seascape spatial pattern on the trophic niche of an omnivorous fish. ECOSPHERE, 13(2), 18 pages. [doi](https://doi.org/10.1002/ecs2.3944)

29\. *James, W. R.*, **Santos, R. O.**, **Rehage, J. S.**, Doerr, J. C., & Nelson, J. A. (2022). <i>E-scape</i>: Consumer-specific landscapes of energetic resources derived from stable isotope analysis and remote sensing. JOURNAL OF ANIMAL ECOLOGY, 91(2), 381-390. [doi](https://doi.org/10.1111/1365-2656.13637)

28\. Gervasi, C. L., **Santos, R. O.**, *Rezek, R. J.*, *James, W. R.*, Boucek, R. E., Bradshaw, C., . . . **Rehage, J. S.** (2022). Bottom-up conservation: using translational ecology to inform conservation priorities for a recreational fishery. CANADIAN JOURNAL OF FISHERIES AND AQUATIC SCIENCES, 79(1), 47-62. [doi](https://doi.org/10.1139/cjfas-2021-0024)


27\. *James, W. R.*, Topor, Z. M., & **Santos, R. O.** (2021). Seascape Configuration Influences the Community Structure of Marsh Nekton. ESTUARIES AND COASTS, 44(6), 1521-1533. [doi](https://doi.org/10.1007/s12237-020-00853-7)


26\. **Rodemann, J. R.<sup>†</sup>**, *James, W. R.*, **Santos, R. O.**, Furman, B. T., Fratto, Z. W., **Bautista, V.<sup>*</sup>**, . . . **Rehage, J. S.** (2021). Impact of Extreme Disturbances on Suspended Sediment in Western Florida Bay: Implications for Seagrass Resilience. FRONTIERS IN MARINE SCIENCE, 8, 13 pages. [doi](https://doi.org/10.3389/fmars.2021.633240)

25\. Pittman, S. J., Yates, K. L., Bouchet, P. J., Alvarez-Berastegui, D., Andrefouet, S., Bell, S. S., . . . Young, M. (2021). Seascape ecology: identifying research priorities for an emerging ocean sustainability science. MARINE ECOLOGY PROGRESS SERIES, 663, 1-29. [doi](https://doi.org/10.3354/meps13661)

24\. Blanchard, J. R., **Santos, R. O.**, & **Rehage, J. S.** (2021). Sociability interacts with temporal environmental variation to spatially structure metapopulations: A fish dispersal simulation in an ephemeral landscape. ECOLOGICAL MODELLING, 443, 11 pages. [doi](https://doi.org/10.1016/j.ecolmodel.2021.109458)

23\. Hogan, J. A., Feagin, R. A., Starr, G., Ross, M., Lin, T.-C., O'connell, C., . . . Patrick, C. J. (2020). A Research Framework to Integrate Cross-Ecosystem Responses to Tropical Cyclones. BIOSCIENCE, 70(6), 477-489. [doi](https://doi.org/10.1093/biosci/biaa034)


22\. *Rezek, R. J.*, **Massie, J. A.<sup>†</sup>**, Nelson, J. A., **Santos, R. O.**, **Viadero, N. M.<sup>†</sup>**, Boucek, R. E., & **Rehage, J. S.** (2020). Individual consumer movement mediates food web coupling across a coastal ecosystem. ECOSPHERE, 11(12), 11 pages. [doi](https://doi.org/10.1002/ecs2.3305)


21\. Koval, G., **Rivas, N.<sup>†</sup>**, D'Alessandro, M., Hesley, D., **Santos, R. O.**, & Lirman, D. (2020). Fish predation hinders the success of coral restoration efforts using fragmented massive corals. PEERJ, 8, 20 pages. [doi](https://doi.org/10.7717/peerj.9978)


20\. Strickland, B. A., **Massie, J. A.<sup>†</sup>**, **Viadero, N.<sup>†</sup>**, **Santos, R. O.**, Gastrich, K. R., Paz, V., . . . Heithaus, M. R. (2020). Movements of Juvenile Bull Sharks in Response to a Major Hurricane Within a Tropical Estuarine Nursery Area. ESTUARIES AND COASTS, 43(5), 1144-1157. [doi](https://doi.org/10.1007/s12237-019-00600-7)

19\. **Massie, J. A.<sup>†</sup>**, Strickland, B. A., **Santos, R. O.**, Hernandez, J., **Viadero, N.<sup>†</sup>**, Boucek, R. E., . . . **Rehage, J. S.** (2020). Going Downriver: Patterns and Cues in Hurricane-Driven Movements of Common Snook in a Subtropical Coastal River. ESTUARIES AND COASTS, 43(5), 1158-1173. [doi](https://doi.org/10.1007/s12237-019-00617-y)

18\. Stipek, C., **Santos, R. O.**, Babcock, E., & Lirman, D. (2020). Modelling the resilience of seagrass communities exposed to pulsed freshwater discharges: A seascape approach. PLOS ONE, 15(2), 15 pages. [doi](https://doi.org/10.1371/journal.pone.0229147)


17\. **Santos, R. O.**, Varona, G., Avila, C. L., Lirman, D., & Collado-Vides, L. (2020). Implications of macroalgae blooms to the spatial structure of seagrass seascapes: The case of the <i>Anadyomene</i> spp. (Chlorophyta) bloom in Biscayne Bay, Florida. MARINE POLLUTION BULLETIN, 150, 12 pages. [doi](https://doi.org/10.1016/j.marpolbul.2019.110742)

16\. **Eggenberger, C. W.<sup>†</sup>**, **Santos, R. O.**, Frankovich, T. A., *James, W. R.*, Madden, C. J., Nelson, J. A., & **Rehage, J. S.** (2019). Coupling telemetry and stable isotope techniques to unravel movement: Snook habitat use across variable nutrient environments. FISHERIES RESEARCH, 218, 35-47. [doi](https://doi.org/10.1016/j.fishres.2019.04.008)

15\. Boucek, R. E., Trotter, A. A., Blewett, D. A., Ritch, J. L., **Santos, R. O.**, Stevens, P. W., . . . **Rehage, J.** (2019). Contrasting river migrations of Common Snook between two Florida rivers using acoustic telemetry. FISHERIES RESEARCH, 213, 219-225. [doi](https://doi.org/10.1016/j.fishres.2018.12.017)

14\. Kroloff, E. K. N., Heinen, J. T., Braddock, K. N., **Rehage, J. S.**, & **Santos, R. O.** (2019). Understanding the decline of catch-and-release fishery with angler knowledge: a key informant approach applied to South Florida bonefish. ENVIRONMENTAL BIOLOGY OF FISHES, 102(2), 319-328. [doi](https://doi.org/10.1007/s10641-018-0812-5)

13\. **Santos, R. O.**, Schinbeckler, R., **Viadero, N.<sup>†</sup>**, Larkin, M. F., Rennert, J. J., Shenker, J. M., & **Rehage, J. S.** (2019). Linking bonefish (<i>Albula vulpes</i>) populations to nearshore estuarine habitats using an otolith microchemistry approach. ENVIRONMENTAL BIOLOGY OF FISHES, 102(2), 267-283. [doi](https://doi.org/10.1007/s10641-018-0839-7)

12\. **Rehage, J. S.**, **Santos, R. O.**, Kroloff, E. K. N., Heinen, J. T., Lai, Q., Black, B. D., . . . Adams, A. J. (2019). How has the quality of bonefishing changed over the past 40 years? Using local ecological knowledge to quantitatively inform population declines in the South Florida flats fishery. ENVIRONMENTAL BIOLOGY OF FISHES, 102(2), 285-298. [doi](https://doi.org/10.1007/s10641-018-0831-2)

11\. **Santos, R. O.**, **Rehage, J. S.**, Kroloff, E. K. N., Heinen, J. T., & Adams, A. J. (2019). Combining data sources to elucidate spatial patterns in recreational catch and effort: fisheries-dependent data and local ecological knowledge applied to the South Florida bonefish fishery. ENVIRONMENTAL BIOLOGY OF FISHES, 102(2), 299-317. [doi](https://doi.org/10.1007/s10641-018-0828-x)

10\. Brownscombe, J. W., Danylchuk, A. J., Adams, A. J., Black, B., Boucek, R., Power, M., . . . Cooke, S. J. (2019). Bonefish in South Florida: status, threats and research needs. ENVIRONMENTAL BIOLOGY OF FISHES, 102(2), 329-348. [doi](https://doi.org/10.1007/s10641-018-0820-5)

9\. **Santos, R. O.**, Lirman, D., Pittman, S. J., & Serafy, J. E. (2018). Spatial patterns of seagrasses and salinity regimes interact to structure marine faunal assemblages in a subtropical bay. MARINE ECOLOGY PROGRESS SERIES, 594, 21-38. [doi](https://doi.org/10.3354/meps12499)

8\. Boucek, R. E., Heithaus, M. R., **Santos, R. O.**, Stevens, P., & **Rehage, J. S.** (2017). Can animal habitat use patterns influence their vulnerability to extreme climate events? An estuarine sportfish case study. GLOBAL CHANGE BIOLOGY, 23(10), 4045-4057. [doi](https://doi.org/10.1111/gcb.13761)

7\. **Santos, R. O.**, **Rehage, J. S.**, Adams, A. J., Black, B. D., Osborne, J., & Kroloff, E. K. N. (2017). Quantitative assessment of a data-limited recreational bonefish fishery using a time-series of fishing guides reports. PLOS ONE, 12(9), 19 pages. [doi](https://doi.org/10.1371/journal.pone.0184776)

6\. **Santos, R. O.**, **Rehage, J. S.**, Boucek, R., & Osborne, J. (2016). Shift in recreational fishing catches as a function of an extreme cold event. ECOSPHERE, 7(6), 16 pages. [doi](https://doi.org/10.1002/ecs2.1335)

5\. **Santos, R. O.**, Lirman, D., & Pittman, S. J. (2016). Long-term spatial dynamics in vegetated seascapes: fragmentation and habitat loss in a human-impacted subtropical lagoon. MARINE ECOLOGY-AN EVOLUTIONARY PERSPECTIVE, 37(1), 200-214. [doi](https://doi.org/10.1111/maec.12259)

4\. Lirman, D., Thyberg, T., **Santos, R.**, Schopmeyer, S., Drury, C., Collado-Vides, L., . . . Serafy, J. (2014). SAV Communities of Western Biscayne Bay, Miami, Florida, USA: Human and Natural Drivers of Seagrass and Macroalgae Abundance and Distribution Along a Continuous Shoreline. ESTUARIES AND COASTS, 37(5), 1243-1255. [doi](https://doi.org/10.1007/s12237-014-9769-6)

3\. **Santos, R. O.**, & Lirman, D. (2012). Using habitat suitability models to predict changes in seagrass distribution caused by water management practices. CANADIAN JOURNAL OF FISHERIES AND AQUATIC SCIENCES, 69(8), 1380-1388. [doi](https://doi.org/10.1139/F2012-018)

2\. **Santos, R. O.**, Lirman, D., & Serafy, J. E. (2011). Quantifying freshwater-induced fragmentation of submerged aquatic vegetation communities using a multi-scale landscape ecology approach. MARINE ECOLOGY PROGRESS SERIES, 427, 233-246. [doi](https://doi.org/10.3354/meps08996)

1\. Lirman, D., Thyberg, T., Herlan, J., Hill, C., Young-Lahiff, C., Schopmeyer, S., . . . Drury, C. (2010). Propagation of the threatened staghorn coral Acropora cervicornis: methods to minimize the impacts of fragment collection and maximize production. CORAL REEFS, 29(3), 729-735. [doi](https://doi.org/10.1007/s00338-010-0621-6)

:::
:::















